import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "./menu";

import './sass/main.sass'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu />
        <div id="container-main">
          {children}
        </div>
      </body>
    </html>
  );
}
