import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Menu from "./menu";

import './sass/main.sass'
import Top from "./top";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="page">
          <Menu />
          <div id="page-main">
            <Top />
            <div id="page-content">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
